const paperInputVals = {

    paperName: {
        type: "input",
        label: "Search by newspaper name",
        placeholder: "Name",
        name: 'mainentry_title'
    },
    frequency: {
        type: 'select',
        label: 'Search by frequency of publication',
        name: 'frequency',
        optionVals: [
            { value: 'select', optionTitle: 'Select' },
            { value: 'weekly', optionTitle: 'Weekly' },
            { value: 'Semimontly', optionTitle: 'Semimonthly' },
            { value: 'Irregular', optionTitle: 'Irregular' },
            { value: 'Daily', optionTitle: 'Daily' },
            { value: 'Three times a week', optionTitle: 'Three times a week' },
            { value: 'Semiweekly', optionTitle: 'Semiweeky' },
            { value: 'Monthly', optionTitle: 'Monthly' },
            { value: 'Biweekly', optionTitle: 'Biweekly' },
            { value: 'Bimonthly', optionTitle: 'Bimonthly' },
            { value: 'Wtknc', optionTitle: 'Wtknc' },
            { value: 'q', optionTitle: 'q' },
            { value: 'b', optionTitle: 'b' },
            { value: 'z', optionTitle: 'z' },
            { value: 'c', optionTitle: 'c' },
            { value: 'W', optionTitle: 'W' },
            { value: 'D', optionTitle: 'D' },
            { value: 'S', optionTitle: 'S' },
            { value: 'C', optionTitle: 'C' },
            { value: 'X', optionTitle: 'X' },
            { value: 'W', optionTitle: 'W' },
            { value: 'I', optionTitle: 'I' },
            { value: 'DW', optionTitle: 'DW' },
            { value: 'M', optionTitle: 'M' },
            { value: 'Z', optionTitle: 'Z' },
            { value: 'J', optionTitle: 'J' },
            { value: 'U', optionTitle: 'U' },
            { value: 'CW', optionTitle: 'CW' },
            { value: 'DX', optionTitle: 'DX' },
            { value: 'B', optionTitle: 'B' },
            { value: 'F', optionTitle: 'F' },
            { value: 'N', optionTitle: 'N' },
            { value: 'EM', optionTitle: 'EM' },
            { value: 'O', optionTitle: 'O' },
            { value: 'T', optionTitle: 'T' },
            { value: 'IC', optionTitle: 'IC' },
            { value: 'DCW', optionTitle: 'DCW' },
            { value: 'DI', optionTitle: 'DI' },
            { value: 'ICW', optionTitle: 'ICW' },
            { value: 'CWJ', optionTitle: 'CWJ' },
            { value: 'EZ', optionTitle: 'EZ' },
            { value: 'DIC', optionTitle: 'DIC' },
            { value: 'DC', optionTitle: 'DC' },
            { value: 'WE', optionTitle: 'WE' },
            { value: 'DIW', optionTitle: 'DIW' },
            { value: 'CWZ', optionTitle: 'CWZ' },
            { value: 'WM', optionTitle: 'WM' },
            { value: 'WEZ', optionTitle: 'WEZ' },
            { value: 'EMZ', optionTitle: 'EMZ' },
            { value: 'DM', optionTitle: 'DM' },
            { value: 'WMZ', optionTitle: 'WMZ' },
            { value: 'CJZ', optionTitle: 'CJZ' },
            { value: 'DCJ', optionTitle: 'DCJ' },
            { value: 'XW', optionTitle: 'XW' },
            { value: 'BW', optionTitle: 'BW' },
            { value: 'SM', optionTitle: 'SM' },
            { value: 'WEM', optionTitle: 'WEM' },
            { value: 'IW', optionTitle: 'IW' },
            { value: 'WS', optionTitle: 'WS' },
            { value: 'CJ', optionTitle: 'CJ' },
            { value: 'DN', optionTitle: 'DN' },
            { value: 'WN', optionTitle: 'WN' },
            { value: 'WB', optionTitle: 'WB' },
            { value: 'WMS', optionTitle: 'WMS' },
            { value: 'WCD', optionTitle: 'WCD' },
            { value: 'EW', optionTitle: 'EW' },
            { value: 'MZ', optionTitle: 'MZ' },
            { value: 'EN', optionTitle: 'EN' },
            { value: 'CX', optionTitle: 'CX' },
            { value: 'XI', optionTitle: 'XI' },

        ]
    },
    countyName: {
        type: "input",
        label: "Search by county name",
        placeholder: "County Name",
        name: 'newspaper_county_name'
    },
    cityName: {
        type: "input",
        label: "Search by the newspaper's city name",
        placeholder: "City Name",
        name: 'newspaper_city_name'
    },
    stateName: {
        type: "input",
        label: "Search by state",
        placeholder: "State name or mailcode (GA, WA, CA, etc..)",
        name: 'newspaper_state_name'
    },
    oclc: {
        type: "input",
        label: "Search by OCLC",
        placeholder: "Enter an OCLC value...",
        name: 'oclc'
    },

    copyType: {
        type: 'select',
        label: 'Search by copy type',
        name: 'copy_type',
        optionVals: [
            { value: 'select', optionTitle: 'Select' },
            { value: 'Original', optionTitle: 'Original' },
            { value: 'microfilm master', optionTitle: 'Microfilm master' },
            { value: 'microfilm', optionTitle: 'Microfilm' },
            { value: 'microopaque', optionTitle: 'Microopaque' },
            { value: 'Reprint', optionTitle: 'Reprint' },
            { value: 'MF', optionTitle: 'MF' },
            { value: 'OR', optionTitle: 'OR' },
            { value: 'NULL', optionTitle: 'NULL' },
            { value: ' ', optionTitle: ' ' },
        ]
    },
};

export default paperInputVals;
